#!/bin/bash

chmod +x yii;

for dir in applications/* ; do
  if [ -d "$dir" ]; then
     app="$(basename "${dir}")"
      # Init migrations
      ./yii sys/migrate --app="$app" --app-interactive=0 --interactive=0
      # Init rbac
      ./yii user/rbac/init --app="$app" --app-interactive=0
  fi
done