#!/bin/bash

for dir in applications/* ; do
  if [ -d "$dir" ]; then
     app="$(basename "${dir}")"
     # Init rbac
     php yii user/rbac/init  --app="$app" --app-interactive=0
     # Init migrations
     php yii sys/migrate
  fi
done